name: employee_tracking_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  image_picker: ^0.8.5+3
  google_fonts: ^4.0.3
  http: ^0.13.0
  provider: ^6.0.0
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/Mask_group.png
    - assets/images/User.png
    - assets/images/email.png
    - assets/images/clock.png
    - assets/images/lock.png
    - assets/images/pin.png
    - assets/images/project.png
    - assets/images/Notification.png
    - assets/images/task.png
    - assets/images/progress.png
    - assets/images/history.png
    - assets/images/arrow.png
    - assets/images/share.png
    - assets/images/Logout.png
    - assets/images/edit.png
    - assets/images/plus.png
    - assets/images/profile.png
    - assets/images/alarm.png
    - assets/images/ntask.png
    - assets/images/map.png
    - assets/images/call.png
    - assets/images/back_arrow.png





  uses-material-design: true
